name: rd-component-publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # https://stackoverflow.com/questions/71318659/gitgithub-com-permission-denied-publickey-when-using-yarn-to-install-github
      - name: Build React App
        run: |
          git config --global url."https://github".insteadOf ssh://git@github
          npm install -g pnpm 
          pnpm install
          pnpm run build
        env:
          CI: false